### ISSUE TITLE
requirements pandas not installed

### ISSUE THREAD

**Issue by will-moore** [IDR/idr-py#15]
I was going to provide more pointers to user at https://github.com/IDR/idr-notebooks/issues/67 since we never told them how to use idr-py to get pixel data.

Tried following https://github.com/IDR/idr-py/ README....

```
$ pip install -U idr-py
Collecting idr-py
  Downloading https://files.pythonhosted.org/packages/ad/91/8948de9ff4a76aec735f098f28872e5db4364b98b5f6f1abbe476e613f81/idr-py-0.3.0.tar.gz
Building wheels for collected packages: idr-py
  Running setup.py bdist_wheel for idr-py ... done
  Stored in directory: /Users/wmoore/Library/Caches/pip/wheels/85/e4/67/59c5888cabbd5c3440959e74de07785b85dfecd47ba9c81130
Successfully built idr-py
Installing collected packages: idr-py
  Found existing installation: idr-py 0.2.0
    Uninstalling idr-py-0.2.0:
      Successfully uninstalled idr-py-0.2.0
Successfully installed idr-py-0.3.0
You are using pip version 10.0.0, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```
$ python
Python 2.7.10 (default, Sep 23 2015, 04:34:14) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import idr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/idr/__init__.py", line 4, in <module>
    from attributes import attributes_by_attributes # NOQA
  File "/usr/local/lib/python2.7/site-packages/idr/attributes.py", line 4, in <module>
    import pandas
ImportError: No module named pandas
```

```
$ pip install pandas
```

```
>>> import idr
>>> ImportError: No module named IPython.display
```

At this point I assume that the docs telling me to do ```$ pip install -U idr-py``` is actually not supported or that some info is missing?

**Comment by manics** [comment]
I'm not sure if we officially support installation from pypi. conda definitely works.

**Comment by jburel** [comment]
I used conda since I had issue installing from pypi.
I think we should recommend conda

**Comment by jburel** [comment]
Closing this issue. This works nicely now it can be installed from pypi
e.g. ``pip install idr-py>=0.4.0.dev3``
